<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find cob_hardware_config)/robots/raw-mini/urdf/calibration_default.urdf.xacro" />
	<xacro:include filename="$(find cob_calibration_data)/raw-mini/calibration/calibration_offset.urdf.xacro" />>

	<!-- ***************** -->
	<!-- base calibration -->
	<!-- ***************** -->
	<!-- laser front mount positions | relative to base_link -->
	<xacro:property name="laser_front_x" value="${def_laser_front_x+offset_laser_front_x}"/>
	<xacro:property name="laser_front_y" value="${def_laser_front_y+offset_laser_front_y}"/>
	<xacro:property name="laser_front_z" value="${def_laser_front_z+offset_laser_front_z}"/>
	<xacro:property name="laser_front_roll" value="${def_laser_front_roll+offset_laser_front_roll}"/>
	<xacro:property name="laser_front_pitch" value="${def_laser_front_pitch+offset_laser_front_pitch}"/>
	<xacro:property name="laser_front_yaw" value="${def_laser_front_yaw+offset_laser_front_yaw}"/>

</robot>
